### ISSUE TITLE
What's the suit branch/commit for k8s v1.10.11?

### ISSUE THREAD

**Issue by mJace** [intel/CPU-Manager-for-Kubernetes#220]
I was using CMK release 1.2.2 commit : fc5d19497229ecb9cb22dd69415ced9053b6b987 on k8s 1.9.1. 
When I upgrade my k8s to 1.10.11, there are some problem with cmk.
cmk reconcile discover pod crashed.

```
root@master-1:/home/k200# kubectl get po -o wide
NAME                                         READY     STATUS             RESTARTS   AGE       IP              NODE
cmk-cluster-init-pod                         0/1       Completed          0          22d       10.20.190.200   master-1
cmk-init-install-discover-pod-master-1       0/2       Completed          0          22d       10.244.0.5      master-1
cmk-init-install-discover-pod-minion-1       0/2       Completed          0          22d       10.244.1.5      minion-1
cmk-reconcile-nodereport-ds-master-1-hvb9g   0/2       CrashLoopBackOff   12476      22d       10.244.0.6      master-1
cmk-reconcile-nodereport-ds-minion-1-gjb85   0/2       CrashLoopBackOff   12478      22d       10.244.1.6      minion-1
node-feature-discovery-8dmsf                 0/1       Completed          0          22d       10.20.190.201   minion-1
node-feature-discovery-x8klt                 0/1       Completed          0          22d       10.20.190.200   master-1
``` 

```
root@master-1:/home/k200# kubectl logs cmk-reconcile-nodereport-ds-master-1-hvb9g reconcile 
{
  "reclaimedCpuLists": []
}
Traceback (most recent call last):
  File "/cmk/cmk.py", line 145, in <module>
    main()
  File "/cmk/cmk.py", line 122, in main
    args["--publish"])
  File "/cmk/intel/reconcile.py", line 69, in reconcile
    reconcile_report = reconcile_report_type.create(node_name)
  File "/cmk/intel/third_party.py", line 105, in create
    self.save()
  File "/cmk/intel/third_party.py", line 66, in save
    raise e
  File "/cmk/intel/third_party.py", line 63, in save
    self.api.create_third_party_resource(body)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 878, in create_third_party_resource
    (data) = self.create_third_party_resource_with_http_info(body, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 962, in create_third_party_resource_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 393, in request
    body=body)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/rest.py", line 287, in POST
    body=body)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '174', 'Date': 'Thu, 27 Dec 2018 08:46:04 GMT', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```

```
root@master-1:/home/k200# kubectl logs cmk-reconcile-nodereport-ds-master-1-hvb9g nodereport 
INFO:root:Isolated logical cores: 2,3,4,5,6,38,39,40,41,42
{
..........
..........
..........
              {
                "id": 71,
                "isolated": false
              }
            ],
            "id": 35
          }
        ],
        "id": 1
      }
    }
  }
}
Traceback (most recent call last):
  File "/cmk/cmk.py", line 145, in <module>
    main()
  File "/cmk/cmk.py", line 134, in main
    args["--publish"])
  File "/cmk/intel/nodereport.py", line 66, in nodereport
    node_report = node_report_type.create(node_name)
  File "/cmk/intel/third_party.py", line 105, in create
    self.save()
  File "/cmk/intel/third_party.py", line 66, in save
    raise e
  File "/cmk/intel/third_party.py", line 63, in save
    self.api.create_third_party_resource(body)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 878, in create_third_party_resource
    (data) = self.create_third_party_resource_with_http_info(body, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 962, in create_third_party_resource_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/api_client.py", line 393, in request
    body=body)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/rest.py", line 287, in POST
    body=body)
  File "/usr/local/lib/python3.4/site-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 27 Dec 2018 08:46:04 GMT', 'Content-Type': 'application/json', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

```

Would you tell me if what's the suitable branch/commit for k8s v1.10.11?
or any information/clue to deal this bug for cmk release 1.2.2 on k8s 1.9.1
Thank you.

**Comment by lmdaly** [comment]
@mJace apologies for such a delayed reply. Is this issue solved? Have you upgraded to CMK v1.3.1 and tested?

**Comment by mJace** [comment]
Thank for your reply!
Yes, Right now I use CMK v1.3.1 in K8s v1.12. It works great.

**Comment by lmdaly** [comment]
Great! I'll go ahead and close the issue.
