### ISSUE TITLE
keyerror observed while running isolate command

### ISSUE THREAD

**Issue by DheerajDang** [intel/CPU-Manager-for-Kubernetes#301]
```
/opt/bin/cmk  isolate  --pool=exclusive echo "test" --namespace=cmk-namespace
test
Traceback (most recent call last):
  File "cmk.py", line 216, in <module>
  File "cmk.py", line 151, in main
  File "intel/isolate.py", line 151, in isolate
TypeError: __init__() missing 1 required positional argument: 'cm_namespace'
[344] Failed to execute script cmk
```

**Comment by DheerajDang** [comment]
Issue is fixed in https://github.com/intel/CPU-Manager-for-Kubernetes/pull/291

**Comment by pbrownlow7** [comment]
Hi @DheerajDang, the fix from https://github.com/intel/CPU-Manager-for-Kubernetes/pull/291 will be added in the latest release which I hope to get out in the coming weeks

**Comment by DheerajDang** [comment]
thanks @pbrownlow7
